name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.10'
    - name: Set up sentence transformers  
      run: |
        pip install -U sentence_transformers

    - name: Validate Build
      run: |
        cmake -S .
        make
        ./bin/MajorMindTests
